//! Implementation of `#[deja::recordable]` — generates delegation macros for traits.
//!
//! The generated `delegate_<trait_name>!` macro produces a manually-desugared
//! impl block with `#[track_caller]` on each method's sync entry point, enabling
//! call-site capture via `Location::caller()`.

use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use syn::{FnArg, ItemTrait, Lifetime, Pat, ReturnType, Signature, TraitItem, TraitItemFn, Type};

/// Convert PascalCase to snake_case.
fn to_snake_case(s: &str) -> String {
    let mut result = String::new();
    for (i, c) in s.chars().enumerate() {
        if c.is_uppercase() {
            if i > 0 {
                result.push('_');
            }
            result.push(c.to_lowercase().next().unwrap_or(c));
        } else {
            result.push(c);
        }
    }
    result
}

/// Top-level entry point: given a trait definition, produce the original trait
/// plus a `delegate_<snake_name>!` macro.
pub fn generate(trait_def: ItemTrait, local: bool, opaque: bool) -> TokenStream {
    let trait_name = &trait_def.ident;
    let trait_name_str = trait_name.to_string();
    let macro_name = format_ident!("delegate_{}", to_snake_case(&trait_name_str));
    let replay_macro_name =
        format_ident!("delegate_{}_with_replay", to_snake_case(&trait_name_str));

    // NOTE: We deliberately omit the trait's where clause from the generated impl.
    // The where clauses on Hyperswitch traits constrain concrete types (e.g.,
    // `MerchantConnectorAccount: behaviour::Conversion<...>`), which the compiler
    // can verify from existing impls. Emitting them in the macro would require
    // module paths (like `storage::`, `storage_types::`) that only resolve in
    // the trait-definition crate, not at the macro expansion site.

    // Generate delegation methods for each trait method.
    let delegation_methods: Vec<TokenStream> = trait_def
        .items
        .iter()
        .filter_map(|item| {
            if let TraitItem::Fn(method) = item {
                Some(generate_method(&trait_name_str, method, false, opaque))
            } else {
                None
            }
        })
        .collect();
    let replay_delegation_methods: Vec<TokenStream> = trait_def
        .items
        .iter()
        .filter_map(|item| {
            if let TraitItem::Fn(method) = item {
                Some(generate_method(&trait_name_str, method, true, opaque))
            } else {
                None
            }
        })
        .collect();

    // The macro uses $wrapper, $inner, $hook, $boundary as parameters.
    // `quote!` uses # for interpolation; $ is literal — perfect for macro_rules.
    let macro_export_attr = if local {
        quote! {}
    } else {
        quote! { #[macro_export] }
    };

    quote! {
        #trait_def

        /// Delegation macro generated by `#[deja::recordable]`.
        ///
        /// Invoke as: `delegate_<trait_name>!(WrapperType, inner_field, hook_field, "boundary");`
        ///
        /// For traits with associated types, pass the associated type items in
        /// a final block:
        ///
        /// `delegate_<trait_name>!(WrapperType, inner_field, hook_field, "storage", { type Error = StorageError; });`
        #macro_export_attr
        #[allow(unused_macros)]
        macro_rules! #macro_name {
            ($wrapper:ty, $inner:ident, $hook:ident, $boundary:expr $(, { $($assoc:item)* })?) => {
                impl #trait_name for $wrapper
                {
                    $($($assoc)*)?
                    #(#delegation_methods)*
                }
            };
        }

        /// Replay-enabled delegation macro generated by `#[deja::recordable]`.
        ///
        /// This variant attempts typed replay before calling the inner value, so
        /// each method return type must implement `serde::de::DeserializeOwned`.
        #macro_export_attr
        #[allow(unused_macros)]
        macro_rules! #replay_macro_name {
            ($wrapper:ty, $inner:ident, $hook:ident, $boundary:expr $(, { $($assoc:item)* })?) => {
                impl #trait_name for $wrapper
                {
                    $($($assoc)*)?
                    #(#replay_delegation_methods)*
                }
            };
        }
    }
}

/// Generate a single delegation method.
///
/// For `async fn`, produces a manually-desugared `fn -> Pin<Box<dyn Future>>`
/// with `#[track_caller]` on the sync entry point.
///
/// For non-async `fn`, produces a simple delegation.
fn generate_method(
    trait_name: &str,
    method: &TraitItemFn,
    enable_replay: bool,
    opaque: bool,
) -> TokenStream {
    let sig = &method.sig;
    let method_name = &sig.ident;
    let method_name_str = method_name.to_string();

    // Preserve #[cfg(...)] and other attributes on the method.
    let attrs: Vec<_> = method
        .attrs
        .iter()
        .filter(|a| {
            a.path().is_ident("cfg") || a.path().is_ident("allow") || a.path().is_ident("doc")
        })
        .collect();

    if sig.asyncness.is_some() {
        generate_async_method(
            trait_name,
            &method_name_str,
            sig,
            &attrs,
            enable_replay,
            opaque,
        )
    } else {
        generate_sync_method(
            trait_name,
            &method_name_str,
            sig,
            &attrs,
            enable_replay,
            opaque,
        )
    }
}

/// Generate a manually-desugared async delegation method.
///
/// Transforms `async fn name(&self, args...) -> Ret` into:
/// ```ignore
/// #[track_caller]
/// fn name<'life0, ..., 'async_trait>(&'life0 self, ...) -> Pin<Box<dyn Future<Output = Ret> + Send + 'async_trait>>
/// where 'life0: 'async_trait, ..., Self: 'async_trait
/// {
///     let caller = Location::caller();
///     Box::pin(async move { ... })
/// }
/// ```
fn generate_async_method(
    trait_name: &str,
    method_name: &str,
    sig: &Signature,
    attrs: &[&syn::Attribute],
    enable_replay: bool,
    opaque: bool,
) -> TokenStream {
    let method_ident = &sig.ident;

    // Extract the return type (what comes after ->).
    let return_type = match &sig.output {
        ReturnType::Default => quote!(()),
        ReturnType::Type(_, ty) => quote!(#ty),
    };

    // Assign lifetimes to reference parameters.
    let mut life_counter: usize = 0;
    let mut lifetime_defs: Vec<Lifetime> = Vec::new();

    // Build transformed parameter list and collect arg names for delegation.
    let mut transformed_params: Vec<TokenStream> = Vec::new();
    let mut delegation_args: Vec<TokenStream> = Vec::new();

    for input in &sig.inputs {
        match input {
            FnArg::Receiver(recv) => {
                if recv.reference.is_some() {
                    let lt = Lifetime::new(&format!("'life{}", life_counter), recv.self_token.span);
                    life_counter += 1;
                    lifetime_defs.push(lt.clone());

                    if recv.mutability.is_some() {
                        transformed_params.push(quote!(&#lt mut self));
                    } else {
                        transformed_params.push(quote!(&#lt self));
                    }
                } else {
                    transformed_params.push(quote!(self));
                }
            }
            FnArg::Typed(pat_type) => {
                let pat = &pat_type.pat;
                let ty = &pat_type.ty;

                let arg_name = extract_arg_name(pat);
                delegation_args.push(arg_name);

                if is_reference_type(ty) {
                    let lt = Lifetime::new(
                        &format!("'life{}", life_counter),
                        proc_macro2::Span::call_site(),
                    );
                    life_counter += 1;
                    lifetime_defs.push(lt.clone());

                    let inner_ty = strip_outer_reference(ty);
                    if is_mut_reference(ty) {
                        transformed_params.push(quote!(#pat: &#lt mut #inner_ty));
                    } else {
                        transformed_params.push(quote!(#pat: &#lt #inner_ty));
                    }
                } else {
                    transformed_params.push(quote!(#pat: #ty));
                }
            }
        }
    }

    let async_lt = Lifetime::new("'async_trait", proc_macro2::Span::call_site());

    let life_bounds: Vec<TokenStream> = lifetime_defs
        .iter()
        .map(|lt| quote!(#lt: #async_lt))
        .collect();

    let existing_generics = &sig.generics;
    let extra_params: Vec<_> = existing_generics.params.iter().collect();
    let existing_where_preds: Vec<_> = existing_generics
        .where_clause
        .iter()
        .flat_map(|w| w.predicates.iter())
        .collect();

    let method_name_lit = method_name;
    // Stable rank-3 syntax hash, computed at expansion time over the logical
    // identity of this delegate method (trait + method). Same algorithm as the
    // boundary macro's `syntactic_hash` so both paths agree.
    let syntax_hash_lit =
        crate::instrument::syntactic_hash(&format!("{}::{}", trait_name, method_name));
    let args_json = if opaque {
        build_opaque_args_json(&sig.inputs)
    } else {
        build_args_json(&sig.inputs)
    };
    let result_json_expr = result_json_expr(opaque);
    let replay_bound = if enable_replay {
        quote!(#return_type: ::serde::de::DeserializeOwned,)
    } else {
        quote!()
    };
    // The reconstruct closure handed to the single `dispatch_async_with_hook`
    // seam: on a lookup HIT it turns the recorded JSON back into the return type,
    // returning `None` to FALL THROUGH to live execution (deserialize failure /
    // the V1 "skip error arms" policy). For the record-only delegate it is
    // `|_| None` — UNREACHABLE (the recording hook never returns a lookup hit) —
    // so the `DeserializeOwned` capability is confined to the replay variant's
    // closure and record-only return types compile WITHOUT any serde bound.
    let reconstruct_closure = if enable_replay {
        quote! {
            |__deja_recorded: ::serde_json::Value| -> ::core::option::Option<#return_type> {
                ::serde_json::from_value::<#return_type>(__deja_recorded).ok()
            }
        }
    } else {
        quote! {
            |_: ::serde_json::Value| -> ::core::option::Option<#return_type> {
                ::core::option::Option::None
            }
        }
    };

    quote! {
        #(#attrs)*
        #[track_caller]
        #[allow(clippy::manual_async_fn, clippy::used_underscore_binding)]
        fn #method_ident <#(#lifetime_defs,)* #async_lt #(, #extra_params)*> (
            #(#transformed_params),*
        ) -> ::core::pin::Pin<Box<
            dyn ::core::future::Future<Output = #return_type> + ::core::marker::Send + #async_lt
        >>
        where
            #(#life_bounds,)*
            #(#existing_where_preds,)*
            Self: #async_lt,
            #replay_bound
        {
            // Fast path: skip all recording overhead when the hook is inactive.
            // This stays in the macro (not a replay-only operation — it is the
            // recording gate). On the active path args are serialized eagerly,
            // exactly as before: the async method returns a `Box::pin` future into
            // which both the args image and the run block are moved, which forbids
            // a borrowing lazy args thunk (a returned future cannot borrow locals).
            if !::deja_record::DejaHook::is_active(&*self.$hook) {
                return Box::pin(async move {
                    self.$inner.#method_ident(#(#delegation_args),*).await
                });
            }

            let __deja_caller: &'static ::std::panic::Location<'static> =
                ::std::panic::Location::caller();
            let __deja_receiver = ::serde_json::json!({
                "self_type": ::std::any::type_name::<Self>(),
                "inner_type": ::std::any::type_name_of_val(&self.$inner),
            });
            let __deja_args = #args_json;

            // Build CallsiteIdentity ONCE (occurrence allocated once here and reused
            // by the seam for both the replay lookup and the recorded event). See the
            // pre-`dispatch` rationale: rank-3 SyntacticHash + rank-4 LexicalPath.
            let __deja_correlation_id_for_identity = ::deja_context::current_correlation_id();
            let __deja_identity_scope_string = format!("{}::{}", #trait_name, #method_name_lit);
            let __deja_identity_scope = ::core::option::Option::Some(__deja_identity_scope_string.as_str());
            let __deja_identity = ::deja_record::CallsiteIdentity {
                version: 1,
                source: ::deja_record::CallsiteSource::SyntacticHash,
                id: ::core::option::Option::None,
                scope: ::core::option::Option::Some(__deja_identity_scope_string.clone()),
                occurrence: ::deja_record::DejaHook::next_callsite_occurrence(
                    &*self.$hook,
                    __deja_correlation_id_for_identity.as_deref(),
                    ::deja_record::CallsiteSource::SyntacticHash,
                    __deja_identity_scope,
                ),
                caller_function: ::core::option::Option::Some(::std::module_path!().to_string()),
                lexical_path: ::core::option::Option::Some(::std::module_path!().to_string()),
                syntax_hash: ::core::option::Option::Some(#syntax_hash_lit),
                logical_context: ::deja_record::current_logical_span_path(),
            };

            // ONE seam: collapses the former execute / replay / record arms into a
            // single call that owns all run/skip/shadow/record control flow. The
            // delegate macro names NO replay-only operation. The seam yields the
            // method's return type; the macro re-wraps it in the `Box::pin` the
            // manually-desugared async-trait signature requires.
            Box::pin(::deja_record::dispatch_async_with_hook(
                ::deja_record::DelegateObservation {
                    hook: &*self.$hook,
                    boundary: $boundary,
                    trait_name: #trait_name,
                    method_name: #method_name_lit,
                    caller: __deja_caller,
                    identity: __deja_identity,
                    receiver: ::core::option::Option::Some(__deja_receiver),
                },
                __deja_args,
                move || async move {
                    self.$inner.#method_ident(#(#delegation_args),*).await
                },
                #reconstruct_closure,
                move |__deja_result| { #result_json_expr },
            ))
        }
    }
}

/// Generate a simple sync delegation method with recording support.
fn generate_sync_method(
    trait_name: &str,
    method_name: &str,
    sig: &Signature,
    attrs: &[&syn::Attribute],
    enable_replay: bool,
    opaque: bool,
) -> TokenStream {
    let method_ident = &sig.ident;
    let params = &sig.inputs;
    let return_type = &sig.output;
    let generics = &sig.generics;
    let (method_generics, _, existing_where_clause) = generics.split_for_impl();
    let return_type_for_bound = output_type_tokens(return_type);

    let delegation_args: Vec<TokenStream> = sig
        .inputs
        .iter()
        .filter_map(|input| {
            if let FnArg::Typed(pat_type) = input {
                Some(extract_arg_name(&pat_type.pat))
            } else {
                None
            }
        })
        .collect();

    let method_name_lit = method_name;
    // Stable rank-3 syntax hash over trait + method (same algorithm as the
    // boundary macro and the async delegate method).
    let syntax_hash_lit =
        crate::instrument::syntactic_hash(&format!("{}::{}", trait_name, method_name));
    let args_json = if opaque {
        build_opaque_args_json(&sig.inputs)
    } else {
        build_args_json(&sig.inputs)
    };
    let result_json_expr = result_json_expr(opaque);
    let where_clause = sync_where_clause(generics, enable_replay.then_some(return_type_for_bound));
    let where_clause = if enable_replay {
        where_clause
    } else {
        quote!(#existing_where_clause)
    };
    // The reconstruct closure for the single `dispatch_with_hook` seam (sync
    // analogue of the async method). Record-only → `|_| None` (unreachable, no
    // serde bound); replay → deserialize the return type, `None` falls through.
    let reconstruct_closure = if enable_replay {
        let return_type_for_replay = output_type_tokens(return_type);
        quote! {
            |__deja_recorded: ::serde_json::Value| -> ::core::option::Option<#return_type_for_replay> {
                ::serde_json::from_value::<#return_type_for_replay>(__deja_recorded).ok()
            }
        }
    } else {
        let return_type_for_replay = output_type_tokens(return_type);
        quote! {
            |_: ::serde_json::Value| -> ::core::option::Option<#return_type_for_replay> {
                ::core::option::Option::None
            }
        }
    };

    quote! {
        #(#attrs)*
        #[track_caller]
        fn #method_ident #method_generics (#params) #return_type
        #where_clause
        {
            // Fast path: skip all recording overhead when the hook is inactive
            // (recording gate, not a replay-only operation). On the active path
            // args are serialized eagerly so the seam call needs no borrowing
            // thunk — matching the boxed-future constraint of the async sibling.
            if !::deja_record::DejaHook::is_active(&*self.$hook) {
                return self.$inner.#method_ident(#(#delegation_args),*);
            }

            let __deja_caller: &'static ::std::panic::Location<'static> =
                ::std::panic::Location::caller();
            let __deja_receiver = ::serde_json::json!({
                "self_type": ::std::any::type_name::<Self>(),
                "inner_type": ::std::any::type_name_of_val(&self.$inner),
            });
            let __deja_args = #args_json;

            // Build CallsiteIdentity ONCE (occurrence allocated once, reused by the
            // seam for the lookup and the recorded event). Same rank-3/4 scheme.
            let __deja_correlation_id_for_identity = ::deja_context::current_correlation_id();
            let __deja_identity_scope_string = format!("{}::{}", #trait_name, #method_name_lit);
            let __deja_identity_scope = ::core::option::Option::Some(__deja_identity_scope_string.as_str());
            let __deja_identity = ::deja_record::CallsiteIdentity {
                version: 1,
                source: ::deja_record::CallsiteSource::SyntacticHash,
                id: ::core::option::Option::None,
                scope: ::core::option::Option::Some(__deja_identity_scope_string.clone()),
                occurrence: ::deja_record::DejaHook::next_callsite_occurrence(
                    &*self.$hook,
                    __deja_correlation_id_for_identity.as_deref(),
                    ::deja_record::CallsiteSource::SyntacticHash,
                    __deja_identity_scope,
                ),
                caller_function: ::core::option::Option::Some(::std::module_path!().to_string()),
                lexical_path: ::core::option::Option::Some(::std::module_path!().to_string()),
                syntax_hash: ::core::option::Option::Some(#syntax_hash_lit),
                logical_context: ::deja_record::current_logical_span_path(),
            };

            // ONE seam: the former execute / replay / record arms collapse into a
            // single call that owns all control flow. Names NO replay-only op.
            ::deja_record::dispatch_with_hook(
                ::deja_record::DelegateObservation {
                    hook: &*self.$hook,
                    boundary: $boundary,
                    trait_name: #trait_name,
                    method_name: #method_name_lit,
                    caller: __deja_caller,
                    identity: __deja_identity,
                    receiver: ::core::option::Option::Some(__deja_receiver),
                },
                __deja_args,
                || self.$inner.#method_ident(#(#delegation_args),*),
                #reconstruct_closure,
                |__deja_result| { #result_json_expr },
            )
        }
    }
}

fn output_type_tokens(output: &ReturnType) -> TokenStream {
    match output {
        ReturnType::Default => quote!(()),
        ReturnType::Type(_, ty) => quote!(#ty),
    }
}

fn sync_where_clause(
    generics: &syn::Generics,
    replay_return_type: Option<TokenStream>,
) -> TokenStream {
    let existing_where_preds: Vec<_> = generics
        .where_clause
        .iter()
        .flat_map(|w| w.predicates.iter())
        .collect();

    if let Some(return_type) = replay_return_type {
        quote! {
            where
                #(#existing_where_preds,)*
                #return_type: ::serde::de::DeserializeOwned
        }
    } else if let Some(where_clause) = &generics.where_clause {
        quote!(#where_clause)
    } else {
        quote!()
    }
}

/// Extract the argument name from a pattern for use in delegation calls.
fn extract_arg_name(pat: &Pat) -> TokenStream {
    match pat {
        Pat::Ident(pat_ident) => {
            let ident = &pat_ident.ident;
            quote!(#ident)
        }
        Pat::Wild(_) => {
            // Wildcard — can't delegate, pass unit
            quote!(())
        }
        Pat::Reference(pat_ref) => {
            // &arg — extract the inner pattern
            extract_arg_name(&pat_ref.pat)
        }
        _ => {
            // Fallback: emit the pattern as-is (may not compile for complex patterns)
            quote!(#pat)
        }
    }
}

/// Extract a string identifier suitable for JSON field keys.
fn extract_arg_key(pat: &Pat) -> Option<String> {
    match pat {
        Pat::Ident(pat_ident) => Some(pat_ident.ident.to_string()),
        Pat::Reference(pat_ref) => extract_arg_key(&pat_ref.pat),
        _ => None,
    }
}

/// Build `serde_json::json!({ "arg1": &arg1, "arg2": &arg2, ... })` for all
/// non-self typed parameters whose patterns yield a simple identifier.
///
/// Uses `&arg` so the original value is borrowed, not moved — this preserves
/// the variable for the subsequent delegation call to `self.$inner.method(...)`.
fn build_args_json(inputs: &syn::punctuated::Punctuated<FnArg, syn::token::Comma>) -> TokenStream {
    let mut entries: Vec<TokenStream> = Vec::new();

    for input in inputs.iter() {
        if let FnArg::Typed(pat_type) = input {
            let pat = &pat_type.pat;
            if let Some(key) = extract_arg_key(pat) {
                let key_lit = syn::LitStr::new(&key, proc_macro2::Span::call_site());
                let val = extract_arg_name(pat);
                entries.push(quote!(#key_lit: &#val));
            }
        }
    }

    if entries.is_empty() {
        quote!(::serde_json::json!({}))
    } else {
        quote!(::serde_json::json!({ #(#entries),* }))
    }
}

fn build_opaque_args_json(
    inputs: &syn::punctuated::Punctuated<FnArg, syn::token::Comma>,
) -> TokenStream {
    let mut entries: Vec<TokenStream> = Vec::new();

    for input in inputs.iter() {
        if let FnArg::Typed(pat_type) = input {
            let pat = &pat_type.pat;
            let ty = &pat_type.ty;
            if let Some(key) = extract_arg_key(pat) {
                let key_lit = syn::LitStr::new(&key, proc_macro2::Span::call_site());
                entries.push(quote! {
                    #key_lit: ::serde_json::json!({
                        "deja_opaque_type": ::std::any::type_name::<#ty>()
                    })
                });
            }
        }
    }

    if entries.is_empty() {
        quote!(::serde_json::json!({}))
    } else {
        quote!(::serde_json::json!({ #(#entries),* }))
    }
}

fn result_json_expr(opaque: bool) -> TokenStream {
    if opaque {
        quote! {
            (
                ::serde_json::json!({
                    "deja_opaque_type": ::std::any::type_name_of_val(&__deja_result)
                }),
                false,
            )
        }
    } else {
        quote! {
            match ::serde_json::to_value(&__deja_result) {
                ::core::result::Result::Ok(val) => {
                    let is_err = ::deja_record::serialized_result_is_error(&val);
                    (val, is_err)
                }
                ::core::result::Result::Err(_) => (
                    ::serde_json::json!({"deja_serialization_error": true}),
                    false,
                ),
            }
        }
    }
}

/// Check if a type is a top-level reference (`&T` or `&mut T`).
fn is_reference_type(ty: &Type) -> bool {
    matches!(ty, Type::Reference(_))
}

/// Check if a type is a mutable reference (`&mut T`).
fn is_mut_reference(ty: &Type) -> bool {
    if let Type::Reference(ref_type) = ty {
        ref_type.mutability.is_some()
    } else {
        false
    }
}

/// Strip the outer `&` or `&mut` from a reference type, returning the inner type.
fn strip_outer_reference(ty: &Type) -> &Type {
    if let Type::Reference(ref_type) = ty {
        &ref_type.elem
    } else {
        ty
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn snake_case_conversion() {
        assert_eq!(to_snake_case("AddressInterface"), "address_interface");
        assert_eq!(
            to_snake_case("PaymentIntentInterface"),
            "payment_intent_interface"
        );
        assert_eq!(to_snake_case("RefundInterface"), "refund_interface");
        assert_eq!(to_snake_case("MCAInterface"), "m_c_a_interface");
    }
}
